<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<a class="vouncher-link" href="<?= $escaper->escapeUrl($block->getUrl('voucher/hunt')); ?>"><?= __('More Voucher'); ?></a> |
<a class="vouncher-link" href="<?= $escaper->escapeUrl($block->getUrl('voucher/wallet/history')); ?>"><?= __('View History Voucher'); ?></a> |
<a class="vouncher-link looking-blog-link" href="<?= $escaper->escapeUrl($block->getUrl('voucher/wallet/history')); ?>"><?= __('Looking for more information'); ?></a>
